### ISSUE TITLE
i want this sript 

### ISSUE THREAD

**Issue by bisegypt-food** [AshrafTaifour/Private-Facebook-Scraper#2]
i looking for this script

**Comment by AshrafTaifour** [comment]
Hello, you may use our source code as long as it's not used for any harm (such as breaking Facebook's terms of service) or commercial use.

**Comment by bisegypt-food** [comment]
Mr. Ashraf, are your code extract personal email and personal emails or just public data pls answer me 

Especially that Facebook block's id in case of ads and are your code achieve my requirements

I waiting your feedback 

Thanks , Mohamed

**Comment by bisegypt-food** [comment]
Mr. Ashraf, are your code extract personal email and personal emails or just public data pls answer me 
Especially that Facebook block's id in case of ads and are your code achieve my requirements
I waiting your feedback 
Thanks , Mohamed

**Comment by bisegypt-food** [comment]
please look my requriments 
![image](https://user-images.githubusercontent.com/70766366/126004251-066a3076-ad8a-459e-9b78-26e6e3ba8184.png)

**Comment by bisegypt-food** [comment]
please i will send my requirement by my email pls check your inbox

**Comment by AshrafTaifour** [comment]
Hello again, I have checked out your requirements, sorry my code only extracts public information. Currently, I have no plans to expand its features.
